openapi: 3.0.3
info:
  title: CUNCTA Verifier Service
  version: 1.0.0-testnet
servers:
  - url: http://localhost:3003
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        "200":
          description: Metrics text
  /v1/verify:
    post:
      summary: Verify presentation
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Verification decision
