export declare const config: {
  NODE_ENV: "development" | "test" | "production";
  PORT: number;
  HEDERA_NETWORK: "testnet" | "previewnet" | "mainnet";
  ALLOW_MAINNET: boolean;
  DEV_MODE: boolean;
  BACKUP_RESTORE_MODE: boolean;
  SERVICE_BIND_ADDRESS: string;
  PUBLIC_SERVICE: boolean;
  TRUST_PROXY: boolean;
  AUTO_MIGRATE: boolean;
  ENFORCE_HTTPS_INTERNAL: boolean;
  DATABASE_URL: string;
  CHALLENGE_TTL_SECONDS: number;
  HEDERA_OPERATOR_ID?: string | undefined;
  HEDERA_OPERATOR_PRIVATE_KEY?: string | undefined;
  POLICY_SIGNING_JWK?: string | undefined;
  POLICY_SIGNING_BOOTSTRAP: boolean;
  POLICY_VERSION_FLOOR_ENFORCED: boolean;
  STRICT_DB_ROLE: boolean;
  ALLOW_LEGACY_SERVICE_JWT_SECRET: boolean;
  SERVICE_JWT_SECRET?: string | undefined;
  SERVICE_JWT_SECRET_POLICY?: string | undefined;
  SERVICE_JWT_SECRET_NEXT?: string | undefined;
  SERVICE_JWT_AUDIENCE: string;
  SERVICE_JWT_AUDIENCE_POLICY: string;
  SERVICE_JWT_SECRET_FORMAT_STRICT: boolean;
  ANCHOR_AUTH_SECRET?: string | undefined;
};
