export declare const config: {
  NODE_ENV: "development" | "test" | "production";
  PORT: number;
  DEV_MODE: boolean;
  BACKUP_RESTORE_MODE: boolean;
  SERVICE_BIND_ADDRESS: string;
  PUBLIC_SERVICE: boolean;
  TRUST_PROXY: boolean;
  LOCAL_DEV: boolean;
  AUTO_MIGRATE: boolean;
  ENFORCE_HTTPS_INTERNAL: boolean;
  ISSUER_SERVICE_BASE_URL: string;
  POLICY_SERVICE_BASE_URL: string;
  ISSUER_JWKS?: string | undefined;
  VERIFIER_AUDIENCE?: string | undefined;
  SDJWT_COMPAT_LEGACY_TYP: boolean;
  ALLOW_INSECURE_DEV_AUTH: boolean;
  ALLOW_LEGACY_SERVICE_JWT_SECRET: boolean;
  PSEUDONYMIZER_PEPPER?: string | undefined;
  PSEUDONYMIZER_ALLOW_LEGACY: boolean;
  STATUS_LIST_FETCH_TIMEOUT_MS: number;
  STATUS_LIST_CACHE_TTL_SECONDS: number;
  STATUS_LIST_CACHE_MAX_ENTRIES: number;
  VERIFY_MAX_PRESENTATION_BYTES: number;
  VERIFY_MAX_NONCE_CHARS: number;
  VERIFY_MAX_AUDIENCE_CHARS: number;
  VERIFY_MAX_DISCLOSURES: number;
  POLICY_SIGNING_JWK?: string | undefined;
  POLICY_VERSION_FLOOR_ENFORCED: boolean;
  SERVICE_JWT_SECRET?: string | undefined;
  SERVICE_JWT_SECRET_VERIFIER?: string | undefined;
  SERVICE_JWT_SECRET_NEXT?: string | undefined;
  SERVICE_JWT_AUDIENCE: string;
  SERVICE_JWT_AUDIENCE_VERIFIER: string;
  SERVICE_JWT_SECRET_FORMAT_STRICT: boolean;
  ANCHOR_AUTH_SECRET?: string | undefined;
  DATABASE_URL: string;
  STRICT_DB_ROLE: boolean;
};
